name: main

on: [ push, pull_request ]

jobs:
  build:
    name: build_and_test_on_${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v7

      - name: install_hatch
        run: pipx install hatch

      - name: run_tests
        run: hatch run all:test -v

      - name: build_dist
        run: hatch build

  tag_and_release:
    name: tag_version
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: install_hatch
        run: pipx install hatch
      - name: get_version
        run: |
          echo "VERSION=$(hatch version)" >> $GITHUB_ENV
      - name: check_if_tag_exists_for_version
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${VERSION}"; then
            echo "Tag ${VERSION} exists."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "Tag ${VERSION} does not exist."
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi
      - name: create_release_tag
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.TAG_EXISTS == 'false' }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.VERSION}`,
              sha: context.sha,
            })
      - name: create_release_from_tag
        uses: softprops/action-gh-release@v2
        if: ${{ env.TAG_EXISTS == 'false' }}
        with:
          tag_name: ${{ env.VERSION }}

  documentation_to_pages:
    name: documentation_to_pages
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install_dependencies
        run: |
          pip install .

      - name: build_documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: setup_pages
        uses: actions/configure-pages@v6

      - name: upload_pages_artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: deploy_pages
        id: deployment
        uses: actions/deploy-pages@v4
